package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/teabranch/abbyfile/pkg/registry"
	"github.com/teabranch/abbyfile/pkg/subagent"
)

// agentFilePlan is a checked, not yet written, install of the sub-agent
// file abby build emitted for an agent.
type agentFilePlan struct {
	Src, Dst string
	Content  []byte
	Version  string // from the file's provenance marker
	SHA256   string
}

// builtAgentFile is where abby build (with --subagent, or for a
// binary: false agent) leaves an agent's sub-agent file.
func builtAgentFile(name string) string {
	return filepath.Join("build", ".claude", "agents", name+".md")
}

// agentFileDir is where Claude Code discovers sub-agents for the scope:
// ~/.claude/agents for --global, else <project>/.claude/agents.
func agentFileDir(opts installOptions) (string, error) {
	if opts.Global {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("getting home dir: %w", err)
		}
		return filepath.Join(home, ".claude", "agents"), nil
	}
	root := opts.ProjectRoot
	if root == "" {
		cwd, err := os.Getwd()
		if err != nil {
			return "", fmt.Errorf("getting working directory: %w", err)
		}
		root = cwd
	}
	return filepath.Join(root, ".claude", "agents"), nil
}

func sha256Hex(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

// planAgentFile checks the built sub-agent file for name and where it
// would go. It returns nil, nil when abby build emitted no file for it, or
// when binVersion is set (a compiled agent) and the file is from another
// version: that file is stale, so it is skipped before the overwrite check
// can refuse on its behalf.
func planAgentFile(name, binVersion string, opts installOptions) (*agentFilePlan, error) {
	src := builtAgentFile(name)
	content, err := os.ReadFile(src)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", src, err)
	}
	marked, version, ok := subagent.ParseMarker(content)
	if !ok || marked != name {
		return nil, fmt.Errorf("%s was not generated by abby build for %q (no matching provenance marker); rebuild it with abby build", src, name)
	}
	if binVersion != "" && version != binVersion {
		fmt.Fprintf(opts.Err, "note: skipping %s: it is v%s but the binary is v%s (rebuild with abby build --subagent to refresh it)\n", src, version, binVersion)
		return nil, nil
	}
	dir, err := agentFileDir(opts)
	if err != nil {
		return nil, err
	}
	p := &agentFilePlan{
		Src:     src,
		Dst:     filepath.Join(dir, name+".md"),
		Content: content,
		Version: version,
		SHA256:  sha256Hex(content),
	}
	if err := checkReplace(name, p, opts.Force); err != nil {
		return nil, err
	}
	return p, nil
}

// checkReplace refuses to overwrite an existing file unless it already
// matches, or is the file abby installed and nobody has edited since, or
// force is set. A hand-maintained agent file is never lost by accident.
func checkReplace(name string, p *agentFilePlan, force bool) error {
	cur, err := os.ReadFile(p.Dst)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading %s: %w", p.Dst, err)
	}
	if force || bytes.Equal(cur, p.Content) {
		return nil
	}
	if e, ok := lookupEntry(name); ok && e.AgentFile == p.Dst && e.AgentFileSHA256 == sha256Hex(cur) {
		return nil
	}
	return fmt.Errorf("%s already exists and was not installed by abby, or was edited since; rerun with --force to replace it", p.Dst)
}

// lookupEntry returns name's registry entry; ok is false when there is
// none or the registry can't be read.
func lookupEntry(name string) (registry.Entry, bool) {
	regPath, err := registry.DefaultPath()
	if err != nil {
		return registry.Entry{}, false
	}
	reg, err := registry.Load(regPath)
	if err != nil {
		return registry.Entry{}, false
	}
	return reg.Get(name)
}

// writeAgentFile writes a planned sub-agent file (or, DryRun, says it would).
func writeAgentFile(p *agentFilePlan, opts installOptions) error {
	if opts.DryRun {
		fmt.Fprintf(opts.Out, "would install %s → %s\n", p.Src, p.Dst)
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(p.Dst), 0o755); err != nil {
		return fmt.Errorf("creating agents dir: %w", err)
	}
	if err := os.WriteFile(p.Dst, p.Content, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", p.Dst, err)
	}
	fmt.Fprintf(opts.Out, "Installed %s → %s\n", p.Src, p.Dst)
	return nil
}

// installFileOnly installs a binary: false agent: its sub-agent file and a
// registry entry, with no binary and no MCP config entry.
func installFileOnly(name string, p *agentFilePlan, opts installOptions) ([]appliedChange, error) {
	if err := writeAgentFile(p, opts); err != nil || opts.DryRun {
		return nil, err
	}
	return nil, trackInstall(registry.Entry{
		Name:            name,
		Source:          "local",
		Version:         p.Version,
		Scope:           regScopeFor(opts.Global),
		AgentFile:       p.Dst,
		AgentFileSHA256: p.SHA256,
	})
}

// builtFileOnlyAgents lists agents with a built sub-agent file but no
// binary in build/ (the binary: false agents).
func builtFileOnlyAgents(binaries map[string]bool) []string {
	entries, err := os.ReadDir(filepath.Dir(builtAgentFile("x")))
	if err != nil {
		return nil
	}
	var names []string
	for _, e := range entries {
		name, ok := strings.CutSuffix(e.Name(), ".md")
		if ok && !e.IsDir() && !binaries[name] {
			names = append(names, name)
		}
	}
	return names
}

// agentFileChecks reports on an installed sub-agent file: missing, edited
// since install, or at a different version from the registry entry (for a
// compiled agent, the binary's version). nil when no file was installed.
func agentFileChecks(e registry.Entry) []check {
	if e.AgentFile == "" {
		return nil
	}
	content, err := os.ReadFile(e.AgentFile)
	if err != nil {
		return []check{{statusFail, fmt.Sprintf("agent file %s is missing or unreadable — reinstall with `abby install %s`", e.AgentFile, e.Name)}}
	}
	cs := []check{{statusOK, "agent file " + e.AgentFile}}
	if sha256Hex(content) != e.AgentFileSHA256 {
		cs = append(cs, check{statusWarn, fmt.Sprintf("agent file edited since install — `abby install --force %s` restores the built version", e.Name)})
	}
	if _, version, ok := subagent.ParseMarker(content); ok && version != e.Version {
		cs = append(cs, check{statusWarn, fmt.Sprintf("agent file is v%s but %s is v%s — rebuild and reinstall to bring them in line", version, e.Name, e.Version)})
	}
	return cs
}

// removeAgentFile deletes an installed sub-agent file unless it was edited
// since install, in which case it is left in place with a note.
func removeAgentFile(e registry.Entry, opts installOptions) error {
	if e.AgentFile == "" {
		return nil
	}
	content, err := os.ReadFile(e.AgentFile)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading %s: %w", e.AgentFile, err)
	}
	if sha256Hex(content) != e.AgentFileSHA256 {
		fmt.Fprintf(opts.Err, "note: %s was edited since install, so it was left in place\n", e.AgentFile)
		return nil
	}
	if opts.DryRun {
		fmt.Fprintf(opts.Out, "would remove %s\n", e.AgentFile)
		return nil
	}
	if err := os.Remove(e.AgentFile); err != nil {
		return fmt.Errorf("removing agent file: %w", err)
	}
	fmt.Fprintf(opts.Out, "Removed %s\n", e.AgentFile)
	return nil
}

// installedPath is what an entry installed: its binary, or for a
// binary: false agent its sub-agent file.
func installedPath(e registry.Entry) string {
	if e.Path != "" {
		return e.Path
	}
	return e.AgentFile
}
